##### ################################################################
#####
#####  Nginx
#####
##### ################################################################
FROM renshi/opensuse-tumbleweed

MAINTAINER Renshi <yanqirenshi@gmail.com>

RUN zypper --non-interactive install nginx