##### ################################################################
#####
#####  Slime
#####
##### ################################################################
FROM renshi/opensuse-tumbleweed-emacs
FROM renshi/opensuse-tumbleweed-roswell

MAINTAINER Renshi <yanqirenshi@gmail.com>

# Switch User
USER cl-user
WORKDIR /home/cl-user

# .emacs.d/dist を作成

# Clone Git Repository
# https://github.com/yanqirenshi/emacs.git
# https://github.com/slime/slime.git
# https://github.com/deadtrickster/slime-repl-ansi-color.git

# .emacs.d/init.lisp
