##### ################################################################
#####
#####  Slime
#####
##### ################################################################
FROM renshi/opensuse-tumbleweed-roswell

MAINTAINER Renshi <yanqirenshi@gmail.com>

# Switch User
USER cl-user
WORKDIR /home/cl-user
