##### ################################################################
#####
#####    Base
#####    ====
#####      https://cloud.docker.com/repository/registry-1.docker.io/renshi/dev
#####
#####    Build
#####    -----
#####      docker build -t renshi/dev -f Dockerfile.Base .
#####
#####    Run
#####    ---
#####      docker run -it renshi/dev /bin/bash
#####
##### ################################################################
FROM renshi/base

MAINTAINER Renshi <yanqirenshi@gmail.com>

USER cl-user
WORKDIR /home/cl-user

RUN mkdir -p  /home/cl-user/.ssh/
RUN chmod 700 /home/cl-user/.ssh/

COPY --chown=cl-user:cl-users .ssh/config /home/cl-user/.ssh/
COPY --chown=cl-user:cl-users .ssh/id_rsa /home/cl-user/.ssh/

RUN chmod 700 /home/cl-user/.ssh/*
